### PR TITLE
Add support for Swift

### PR DESCRIPTION
**Pull request by dppeak**
Added support for Swift:
UIColor(white: x, alpha: x)
UIColor(red: x, green: x, blue: x, alpha: x)
UIColor.constantColor()

### CODE REVIEW

**Comment by dppeak** [comment]
Any chance of getting this merged in soon?

**Comment by BenSS** [comment]
Would love to see this in too.

**Comment by tomaskraina** [comment]
@omz Would love to merge this one too! ;)

**Comment by AlexandarBAT** [comment]
Please merge this

**Comment by danielhauagge** [comment]
This would be great. Any reason it hasn't been merged yet?

**Comment by controversial** [comment]
Pretty sure @omz has stopped watching many of his open-source projects. I sent him a note on Twitter, though.

**Pull request closed without merging**
